#!/usr/bin/env python
#!/usr/bin/env python
""" Get the user input including input images dir and send a message to the
    detection server, receive the detections as a list of string lines & save them
    into the output folder.
"""

import zmq
import sys
import os
import yaml
import argparse

__author__ = "vahid jani"
__copyright__ = "Copyright 2021, The Blurring Project"
__credits__ = ["Vahid jani"]
__license__ = "MIT"
__version__ = "1.0.0"
__maintainer__ = "Vahid jani"
__email__ = "aghajanivahid1@gmail.com"
__status__ = "Development"
